server:
    port: 8080
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true

spring:
    profiles:
        active: local

mybatis:
    config-location: classpath:/mybatis-config.xml
    mapper-locations: classpath:/mybatis/**/*.xml

---

spring:
    jackson:
        property-naming-strategy: LOWER_CAMEL_CASE
    datasource:
        url: jdbc:log4jdbc:oracle:thin:@192.168.0.140:11521:orcl
        username: vims2
        password: oracle12c$vims2#
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    thymeleaf:
        cache: false
        check-template-location: true
        prefix: classpath:/templates/
        suffix: .html
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
    messages:
        basename : exceptionMessage
        encoding : UTF-8
logging:
    level:
        root: info
        com.core: debug